version: '3.8'

volumes:
  db-data:

services:
  product-register:
    container_name: product-register
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/product-register
    environment:
      - DATABASE_PASSWORD=postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    images: postgres
    volumes:
      - db-data:/var/lib/postgresql/data