version: '3.8'

services:
  product-register:
    container_name: product-register
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/product-register
    tty: true
    stdin_open: true